# -*- coding: utf-8 -*-
# Generated by Django 1.11.17 on 2019-06-20 14:36
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('questions', '0005_comment'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comment',
            name='url',
        ),
        migrations.RemoveField(
            model_name='user',
            name='url',
        ),
    ]
