# -*- coding: utf-8 -*-
# Generated by Django 1.11.17 on 2019-06-21 10:03
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('questions', '0008_auto_20190621_1750'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='question',
            name='click_count',
        ),
        migrations.AddField(
            model_name='question',
            name='successCount',
            field=models.IntegerField(default=0, verbose_name='\u6210\u529f\u6b21\u6570'),
        ),
    ]
