# -*- coding: utf-8 -*-
# Generated by Django 1.11.17 on 2019-06-21 14:15
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('questions', '0011_auto_20190621_1855'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='count',
            field=models.IntegerField(default=0, verbose_name='\u6240\u6709\u6b21\u6570'),
        ),
    ]
